language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-29.0.3
  - android-29
  - extra-android-m2repository
  licenses:
  - android-sdk-license-.+
script:
- "./gradlew clean cleanBuildCache check --stacktrace --rerun-tasks"
after_success:
- tools/release/deploy_snapshot.sh
- bash <(curl -s https://codecov.io/bash)
after_script:
- tools/release/deploy_cleanup.sh
before_install:
- yes | sdkmanager "platforms;android-29"
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: false
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
env:
  global:
  - secure: MgsgujnAKOEjeNuP2XWgVvfQ1L+PcWI56p2c4x2jhTdWPMQvLQ1udxgdXTv8X5pB2L4WYUNGcUrE4lVE9Nf71Bjf3zQLc4JIus4j3PVbjbR9xydhntdJsLN/q0GJPmHB+Dr22BvSbXCz6K9Aa0ZX19Sv/yaS6FrOdWrSJMusUx9YEkngipBKffjMHKbFHWlWQXLKWk/BnXu9qzkK9Wd8UzDm9c5C0fOfb9ZhuDLGu19tEuJreFxF3uwh4eG5SgLrZMsXr3EMst9cjeTWBXT9XuUSnANKnlMo/jWXPrW4DIoAtENuc2cGoues/wHkleItK/IbVIarMAx9S5jC2v4xasxjZKMYKuzYUYpzwAz8oww3+qmFiXq6SzmU7Wt2Qlv4I5thrb5cRFXAYvegwQMqY/7yULfC1MkjTQ/1xG4UZ10n1Fh/8HeLIRxgbQtQVAId/VWqZF6EKXBv3IFqJxsbTvyheEQTerUU7eh5XHlKZG1msZ4nWpMpVd6pEjuUuZy7M+ECOe6nCK18Dj8xGrVm/iVWHVzWOYRYspv9fED63BVqWd7MrLvKCfuQFQXlNAgywB6x4EX8uK1g/G9nWF+D5c5Uro/92t8BHtGyXpGcknfE9FDMYuvLi0cfl2hPiUz3dOdymtkwb91RvWgl1Oip/SZ9CKEOVYLOKQcTD5fJ03M=
  - secure: mgGms+1Awefw2PsjQNmvqfuRtx9zSWwdbW+F3GanbjEXCG+tkNyeI0ksBEAMkTEArd5jGBt79oTnnz3kUrGi5l4NzRjH/Mp5ko51SLqgHYINC3yWxgtEkmnmmZMCmvSu+N5/vI7y5RMB2UXQbWkr2OhFCrnHTq2HHzDv/GfxWKmvAO7esri61jVry/GPhrFRCegMV1QT/S9cO0P86jsWVNMe+8xwfaZ4Dea2KoLI8BIl09b/B/CjSGFAByi1W7KIf7QifQmgjVaEEaGFnuRODyW7AiNmbLf+jmu9Dyr+bv7A91+tYsuyZTknRXeJXEVBKDA5wQW7JtmJp2ixoYID4YIsx2hOph+44BEsz781uDfyL+rCvNvf04Nw7sQ0i1wG0MY64SrnTUErMcyeGBJnmCyVCqi7ZmhcGSePips4p8u9p3Z4CKie8kDekYdB44VMhdvQ5qHePoWssWRtb1glcGa8F0SVn/ANXaKAkotuf0Uw1s1C3bK4mHtE5zkWQVPiu5XpMuVL+ZyvtXObai+uwYJ8Uw3YiPbl+mjGYSbDj8p/8utL+QsGg4Dv0KLvNeQQ2OCKGEafsAMWSIlkaSOHXHe39KlPD79FYSjbsILkfjFpTHTZk5R1N9uP+pPd6fO1gEbiKIm9gHlA/PBMqWx9Dqfj3hUTMlfAIUAy3bYXX6E=
  - secure: TEMf1hIh03uXOpQ5FuEETQ9gSCw7StnSYRdE5jNNA4tOG0aReRXMGxD1t2aUR/P3mO+Zqqj6+QshL/sJuelchm7ZIAVIrv375bqxVjjnXXoGbrUxE0YG68HvipeYRSd2/fa8IcZywAn21d2cB7iQUZc4PITRQ6vD2q/xeeXqIxdPlC6jKqTTeP7PL1nqd7dN8xGRK2mLwt42Uv1iZPygLi3FB7gekKFqlDLWJk7wQWNl7N7MMX+qWXW3RTfe4FhaA3LZY7zTcL1IONDV1OHIa3+8IIrXAFXRw+VWrlznWNxLMpL4kyuocrj4e3VFIe1xogW61NA6Q1w/dVp0L4iFqWKoq9gOi+K+zQbAXbb7rxRytkazhWQax3uRlMrs57BAYxyWjxZC/a2uv1zTva/FoptaLBfsPqJ2SWOskPMgynExzGji4XZzgUEGTO3QAU+jA4G5AA3ZAZKjki8LJsYzs2vWNw5sMmxZxIE0260bS+w0UQI2g878xN7RAk1V+Kjxvj9r1W5Tj1sLFwrsh2S0XrSgMDx74ah8ITFKb99jq2xI8LJeMOw3R+pi9LX6Cz9bPaTV1cf0qUnlN5yn9HEraFHRl5AcsXo+P+ut9nFidV3Q/6x2caJmFm49B92vKF7NZ9e6RvOq+vY3PuSDe6VEhmbiKuoOOJUujhsb5RR28pU=
  - secure: lK7nlfB/hPVMmGxGeeFrP5KkHo/exuMlE9BobJW0qjebw6MdT0KVFBpPXaFdg8bo08GljIvvo1mD908/xo9oN4V8Wca9Sqj2Y7YzX/+8ZKZN/WdbW9uR8KAI+uYDksOKTAPjUsqdj7uQHuFu6dcqPc+MlHDrJlqDdXFazd2OXFxxVqrNhGkZwpVEsP8ZBGY3VbY4AskSmzt+XAauPnYGxxK315Ub3Gu15fvH2u2N/6Lj8h6kyjVlpR8rGH+dNXFDxMXc4eQPAK3ZquNox3Ym+0BRFnpbJjH0YomXmYxA0YyktazgcwGlObU1JaxS8U980yNXwzwS1frU3iGuDMDKHkWVJuty5JKSe5ZqZPwy4sM43abmyJ45FRPnREWFOUYVhYnGMKHqMlw2HSy9QEpfkCbV1JKjwLp2R7HBc0r5eK7WOauNSkmPv9WtONDUVgaBf2arIZuhW2NyeKlnApte1QfMJ+IzfgPNr54ZNsZlwu1TZmkBXXc9MZ21iqAWuPa+otCcUTJUZem+ytt37rZwvzRTaCIRyIGBoMGRbKNmEyxiiAQ0Uw0i7l7mEv7pFC6Xn3cS+bR9MRqZn8jWT89aKmD6G7q+raDieG9OQeJzZl+CjVOyj1wBhylCFTNt/S00xPfZsURef/9tvxKh49bABMpgt7sQwWAKIP0udc4W1ZY=
  - secure: x1JDTwdUxMKu8dmsaIhGiTYKzjjAl7zF53ZRd3HAnugK+BmLrbVoBrBvbMzl5itAgghNJKLb4awTMw1tuuDDOXvb581hugWLQphD8yqHDUx0d6/SgTpGXlZcJDO4tc1Iii8W1WQgAcS9wfMBNwI8YfdL83MKPQH7NyOc9uZ1YJUGDejeVKKcIX/0obCXY05ekRLPMi9P5pwvbQKlou2X8Wrq2vEPCXC5R2EvympRd9eYjNXH2NEhOrTggdKvnHafdx1IlwqiCj0saSuO6R+mmVQ8zla5pYReCf6kI1hdBhT7NC/8kk24qfk2khW2HactLTi0AqKlaXt889vc3CGGe68aaUs3B5NvWriObzGsC901lHKXwmGn1tlYE6RlSMkt9P4pLlYkp0xwyj5hJnX/UxiTLMruMXesTlBQ+hWj7NFF57tLPAr4Skv8A4kaiv4x5d7PT0rimDfTpJjF/QVfk6PD9Xu6XqtR7huP9027miHSSBPNI1LBjtIn1DdzhbG7Kqxuu7LYAhsYikmWDbuvI++iQL8QtV7fBQW0Hr5IVYWq8tIC7rx6V+oeobYLy89enHcW+uv5ia5u2yCz002gbkhqunhKkq7R9yDb/YhPE9ASwrPx3hfc6IY42VXcx5LXyyfygRCSAL/tmmzOrDtrXGKN0kGal0u4CyhP5vtktW4=
