language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-29.0.3
  - android-29
  - extra-android-m2repository
  licenses:
  - android-sdk-license-.+
script:
- "./gradlew clean cleanBuildCache check --stacktrace --rerun-tasks"
after_success:
- tools/release/deploy_snapshot.sh
- bash <(curl -s https://codecov.io/bash)
after_script:
- tools/release/deploy_cleanup.sh
before_install:
- yes | sdkmanager "platforms;android-29"
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: false
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
env:
  global:
  - secure: j0J32MA4LGRhCsMIX3Rs/hJdEkxDMgFoPIXr2iz3eRq16VbMEmeWY+ErUvvdd99uj/Jbqb1ss2pwUSiNyUshqTqebEFdEdp9MOvJIs8p6MvkGXtY7k8NnUIzxdduQSIpDet01bJRGQ8hXAyqtASn7ovfftoWwVBkfSf9iSirJf8ax5MsYOR05qK1Tcum7dyklJnliazMEWn/X3fyPGOgpLdvJiwcxZD3XGbXobRH/nG/ssbFnMDuXPk1v3hQeDtpfarDwQwrUcn3x57Ye/gCE3gyyAZ8/FyVsOHoPp7IO+0qjxIDiFvMdxUk/blJb00BjIGrhy9wvy4FmzdLIut8NGXIOdL4B8hKMoZ7qrwyqPuOEi9B7c24Bzr9sI4+5U95RzkKyXoY8LVvV5IsPkGWp2b1Sqct31+qjd7nJAO7Dz3TAX7MaK1k16i+jqKOJ07vaZDiXyyJEGp/PLhDiSxoxDkkZQXxataTesYAsnvhsWjTG06HKCQc5xrdrwa5TcGRjK6TLHj2P3mefwfja+lMnSYdwNuuEwOXxVvoXXrW8erslUHwS4lmDSzxRZOxIE7OxKe8wzZUuy8AF4bQ6PwD1cZqA7VgE/TKM3FHFoxgWLEnB2iPjCpnbvC+1wL2h4sqAy1j1ei1ood38qHjOoQjH3L+DX4B/Wpu84Dbja6Ob+8=
  - secure: HSCyp86U/DT9NuP80QzyfinVt13wa1CQVC4msqU6LymLZTuWgAO5WN5uHFIM5pL5owGjgSYODcVOQjhJYkksj7wUfv9XUX5870vdwYQ5Eof7AOsLg4jeMbNt2FoOHqBFLO/b+xP8Biv8fwB5SY7iQc2XTMQJHsS4ayq7/3B2XsAyFvdBb5hmdq6xXYMzDt98C4ExcXBNqcQ8JnqchVq8JcH7LNNbz7fPq+mkt3kT7HKPLhrer8HSGd1g11d1/E29QkqUZncCG7YSRkZN/kkn1nWNwUqVwcXKuUfgMHghQrzhQg7haTuxgm8Il2GgwNgBZOOo4uxV4NlbLRJn1R2LAzNodAoJoYpEDEnAfkIr/UAovEC7jUghzMVO9aXQwD9+yYL6vS43t1b5PrAz/bKM6sxFl2A8OCKr9rJ5f/BR37b/xiFAfqjWeer+pB/GW7bvdZ4k3ZZgWUln4AXsz9u1w69gJivJvz2cHW8ghja/mAL4TDgyGJVmuI8XbZXnLv0db+XKYZixyhQexf5sThJLA9Sbxa/9s7qfpEqhCMr39ZILnQcEAOhk9aoURBahJgi1ISoyvbL7fNLtU5ZrGcI2HicFRXgr3ixOucBItUX/wQNpDIPtDOnOn+DHSm/bunGOw9SOcVb3JIm0PBRW/dBEb693TlW8ZhVrcAD19FeHab4=
  - secure: TEMf1hIh03uXOpQ5FuEETQ9gSCw7StnSYRdE5jNNA4tOG0aReRXMGxD1t2aUR/P3mO+Zqqj6+QshL/sJuelchm7ZIAVIrv375bqxVjjnXXoGbrUxE0YG68HvipeYRSd2/fa8IcZywAn21d2cB7iQUZc4PITRQ6vD2q/xeeXqIxdPlC6jKqTTeP7PL1nqd7dN8xGRK2mLwt42Uv1iZPygLi3FB7gekKFqlDLWJk7wQWNl7N7MMX+qWXW3RTfe4FhaA3LZY7zTcL1IONDV1OHIa3+8IIrXAFXRw+VWrlznWNxLMpL4kyuocrj4e3VFIe1xogW61NA6Q1w/dVp0L4iFqWKoq9gOi+K+zQbAXbb7rxRytkazhWQax3uRlMrs57BAYxyWjxZC/a2uv1zTva/FoptaLBfsPqJ2SWOskPMgynExzGji4XZzgUEGTO3QAU+jA4G5AA3ZAZKjki8LJsYzs2vWNw5sMmxZxIE0260bS+w0UQI2g878xN7RAk1V+Kjxvj9r1W5Tj1sLFwrsh2S0XrSgMDx74ah8ITFKb99jq2xI8LJeMOw3R+pi9LX6Cz9bPaTV1cf0qUnlN5yn9HEraFHRl5AcsXo+P+ut9nFidV3Q/6x2caJmFm49B92vKF7NZ9e6RvOq+vY3PuSDe6VEhmbiKuoOOJUujhsb5RR28pU=
  - secure: lK7nlfB/hPVMmGxGeeFrP5KkHo/exuMlE9BobJW0qjebw6MdT0KVFBpPXaFdg8bo08GljIvvo1mD908/xo9oN4V8Wca9Sqj2Y7YzX/+8ZKZN/WdbW9uR8KAI+uYDksOKTAPjUsqdj7uQHuFu6dcqPc+MlHDrJlqDdXFazd2OXFxxVqrNhGkZwpVEsP8ZBGY3VbY4AskSmzt+XAauPnYGxxK315Ub3Gu15fvH2u2N/6Lj8h6kyjVlpR8rGH+dNXFDxMXc4eQPAK3ZquNox3Ym+0BRFnpbJjH0YomXmYxA0YyktazgcwGlObU1JaxS8U980yNXwzwS1frU3iGuDMDKHkWVJuty5JKSe5ZqZPwy4sM43abmyJ45FRPnREWFOUYVhYnGMKHqMlw2HSy9QEpfkCbV1JKjwLp2R7HBc0r5eK7WOauNSkmPv9WtONDUVgaBf2arIZuhW2NyeKlnApte1QfMJ+IzfgPNr54ZNsZlwu1TZmkBXXc9MZ21iqAWuPa+otCcUTJUZem+ytt37rZwvzRTaCIRyIGBoMGRbKNmEyxiiAQ0Uw0i7l7mEv7pFC6Xn3cS+bR9MRqZn8jWT89aKmD6G7q+raDieG9OQeJzZl+CjVOyj1wBhylCFTNt/S00xPfZsURef/9tvxKh49bABMpgt7sQwWAKIP0udc4W1ZY=
  - secure: x1JDTwdUxMKu8dmsaIhGiTYKzjjAl7zF53ZRd3HAnugK+BmLrbVoBrBvbMzl5itAgghNJKLb4awTMw1tuuDDOXvb581hugWLQphD8yqHDUx0d6/SgTpGXlZcJDO4tc1Iii8W1WQgAcS9wfMBNwI8YfdL83MKPQH7NyOc9uZ1YJUGDejeVKKcIX/0obCXY05ekRLPMi9P5pwvbQKlou2X8Wrq2vEPCXC5R2EvympRd9eYjNXH2NEhOrTggdKvnHafdx1IlwqiCj0saSuO6R+mmVQ8zla5pYReCf6kI1hdBhT7NC/8kk24qfk2khW2HactLTi0AqKlaXt889vc3CGGe68aaUs3B5NvWriObzGsC901lHKXwmGn1tlYE6RlSMkt9P4pLlYkp0xwyj5hJnX/UxiTLMruMXesTlBQ+hWj7NFF57tLPAr4Skv8A4kaiv4x5d7PT0rimDfTpJjF/QVfk6PD9Xu6XqtR7huP9027miHSSBPNI1LBjtIn1DdzhbG7Kqxuu7LYAhsYikmWDbuvI++iQL8QtV7fBQW0Hr5IVYWq8tIC7rx6V+oeobYLy89enHcW+uv5ia5u2yCz002gbkhqunhKkq7R9yDb/YhPE9ASwrPx3hfc6IY42VXcx5LXyyfygRCSAL/tmmzOrDtrXGKN0kGal0u4CyhP5vtktW4=
